openapi: 3.0.1
info:
  title: Payments API
  description: BearBank Payments API
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/BearBank/PaymentsAPI/1.0.0
paths:
  /payments:
    post:
      summary: Create a payment
      description: Creates a new payment
      operationId: createpayment
      requestBody:
        description: Create a new payments
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payment'
            examples:
              application/json:
                value:
                  id: "1234"
                  account: "Customer 1"
                  price: 42
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                oneOf:
                  - $ref: '#/components/schemas/payment'
              examples:
                application/json:
                  value:
                    id: "1234"
                    account: "Customer 1"
                    price: 42
    get:
      summary: List all payments
      description: Returns all payments
      operationId: getAllPayments
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/payment'
              examples:
                application/json:
                  value:
                    - id: "1234"
                      account: "Customer 1"
                      price: 42
        "400":
          description: Invalid ID supplied
          content: {}
  /payment/{id}:
    get:
      summary: Find payment by ID
      description: Returns a single payment
      operationId: getPaymentByID
      parameters:
      - name: id
        in: path
        description: ID of payment to get
        schema:
          type: string
        required: true
        example: 10
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                $ref: '#/components/schemas/payment'
              examples:
                application/json:
                  value:
                    id: "1234"
                    account: "Customer 1"
                    price: 42
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Payment not found
          content: {}
components:
  schemas:
    payment:
      type: object
      required:
        - id
        - account
        - price
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        version:
          type: string
        price:
          type: number
        account:
          type: string
